// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwauvyvzhhpimevifthj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3YXV2eXZ6aGhwaW1ldmlmdGhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MjI0NjUsImV4cCI6MjA2NDI5ODQ2NX0.De8pVP6brfL5yNmeC6tKSzZBow6kfVqf-n1JljwyGjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);